Embarr.WebAPI.Validation.ExampleWebAPI/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using Embarr.WebAPI.Validation.ExampleWebAPI.Areas.HelpPage.ModelDescriptions;

namespace Embarr.WebAPI.Validation.ExampleWebAPI.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

Embarr.WebAPI.Validation.ExampleWebAPI/Models/ValidationTestModel.cs
using System.ComponentModel.DataAnnotations;

namespace Embarr.WebAPI.Validation.ExampleWebAPI.Models
{
    public class ValidationTestModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [Range(18, 65)]
        public string Age { get; set; }
    }
}

Embarr.WebAPI.Validation.ExampleWebAPI/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Embarr.WebAPI.Validation.ExampleWebAPI.Areas.HelpPage.ModelDescriptions;
using Embarr.WebAPI.Validation.ExampleWebAPI.Areas.HelpPage.Models;

namespace Embarr.WebAPI.Validation.ExampleWebAPI.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Embarr.WebAPI.Validation.ExampleWebAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Embarr.WebAPI.Validation.ExampleWebAPI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

Embarr.WebAPI.Validation.ExampleWebAPI/Controllers/ValuesController.cs
using System.Web.Http;
using Embarr.WebAPI.Validation.ExampleWebAPI.Models;

namespace Embarr.WebAPI.Validation.ExampleWebAPI.Controllers
{
    public class ValuesController : ApiController
    {
        // POST api/values
        public void Post([FromBody]ValidationTestModel value)
        {
        }
    }
}

Embarr.WebAPI.Validation.ExampleWebAPI/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>Web API Request Validator</h1>
    <p class="lead">Utilize DataAnnotations on your ASP.Net Web API models and return your own complex validation models, flattened models or default model state models.</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Model</h2>
        <pre>
public class ValidationTestModel
{
    [Required]
    public string Name { get; set; }

    [Required]
    [Range(18, 65)]
    public string Age { get; set; }
}
</pre>        
    </div>
    <div class="col-md-6">
        <h2>ValuesController Action</h2>
        <pre>
// POST api/values
public void Post([FromBody]ValidationTestModel value)
{
}
</pre>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Showing required data annotation errors</h2>
        <pre>
POST http://localhost:5091/api/values HTTP/1.1
User-Agent: Fiddler
content-type: application/x-www-form-urlencoded
Host: localhost:5091
Content-Length: 10

Name=&Age=
</pre>
        <p>Result:</p>
        <pre>
[{"Property":"Name","Errors":[{"Message":"The Name field is required."}]},{"Property":"Age","Errors":[{"Message":"The Age field is required."}]}]

</pre>
    </div>
    <div class="col-md-6">
        <h2>Showing range data annotation error</h2>
        <pre>
            
POST http://localhost:5091/api/values HTTP/1.1
User-Agent: Fiddler
content-type: application/x-www-form-urlencoded
Host: localhost:5091
Content-Length: 10
Name=&Age=
</pre>
        <p>Result:</p>
        <pre>
[{"Property":"Age","Errors":[{"Message":"The field Age must be between 18 and 65."}]}]
</pre>
    </div>
</div>

Embarr.WebAPI.Validation.ExampleWebAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Web API Request Validator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Embarr Development Limited</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>